### ISSUE TITLE
Tado Heaters

### ISSUE THREAD

**Issue by StefanMeGit** [ckuburlis/homebridge-tado#29]
I dont have a main heater unit, i have 3 different heaters in every room... i 

[https://images.ifun.de/wp-content/uploads/2016/09/tado-homekit-heizkoerper-thermostat.jpg](url)
They only support 16-30C.

i can not go down to 16C... minimum in the HOME-App is still 18 and maximum is 30C.

```
        "accessories": [{
                "accessory": "TADO",
                "name": "TadoLiving",
                "homeID": "XXX",
                "username": "XXX",
                "password": "XXX",
                "zone": 1,
                "maxValue": 25,
                "minValue": 16,
                "useFanSpeed": false,
                "useSwing": false,
                "tadoMode": "TADO-MODE",
                "useFahrenheit": false
        },
        {
                "accessory": "TADO",
                "name": "TadoKittchen",
                "homeID": "XXX",
                "username": "XXX",
                "password": "XXX",
                "zone": 2,
                "maxValue": 25,
                "minValue": 16,
                "useFanSpeed": false,
                "useSwing": false,
                "tadoMode": "TADO-MODE",
                "useFahrenheit": false
        }]

}
```

**Comment by nitaybz** [comment]
that's weird... I don't even have the numbers 18 and 30 set in the code... and I'm not quite sure how my plugin even support the Tado heater cause it is set to work with Tado AC smart control.
but all of this still not explaining those temperatures values.
I'm not sure I can help you control the heater options but lets try to fix the values issue, can you show me a full log of when you restart homebridge - I only care about whats related to this plugin of course. you should see something in the logs like: "Minimum/Maximum setpoint X"

**Comment by nitaybz** [comment]
@StefanMeGit make sure you install the plugin from the git directly:
`sudo npm install -g https://github.com/ckuburlis/homebridge-tado.git`

**Comment by StefanMeGit** [comment]
Sorry for no response, forgot about this the last days! 

After i reinstalled directly from the GIT i got a error on the refresh.. :(
```
[2/5/2017, 5:27:39 PM] [TadoKittchen] The current temperature display unit is ºC
[2/5/2017, 5:27:39 PM] [TadoKittchen] Getting target state
[2/5/2017, 5:27:40 PM] [TadoKittchen] Getting target state
[2/5/2017, 5:27:40 PM] [TadoKittchen] Getting target state
[2/5/2017, 5:27:40 PM] [TadoKittchen] Getting target state
[2/5/2017, 5:27:40 PM] [TadoLiving] Getting target state
[2/5/2017, 5:27:40 PM] [TadoLiving] Getting target state
[2/5/2017, 5:27:40 PM] [TadoLiving] Getting target state
[2/5/2017, 5:27:40 PM] [TadoLiving] The current temperature display unit is ºC
[2/5/2017, 5:27:40 PM] [TadoLiving] Getting target state
[2/5/2017, 5:27:40 PM] [HomeAssistant] fetching power state for: CastLivingRoom
[2/5/2017, 5:27:40 PM] [TadoKittchen] Room temperature is 20.42ºC
[2/5/2017, 5:27:40 PM] [TadoLiving] Room temperature is 23.13ºC
[2/5/2017, 5:27:40 PM] [TadoLiving] Current zone mode is undefined
[2/5/2017, 5:27:40 PM] [TadoLiving] Current power state is ON
[2/5/2017, 5:27:40 PM] [TadoLiving] Target temperature is 21ºC
[2/5/2017, 5:27:40 PM] [TadoLiving] current operating state is AUTO
[2/5/2017, 5:27:40 PM] [TadoKittchen] Target temperature is 20ºC
[2/5/2017, 5:27:40 PM] [TadoKittchen] Target operating state is undefined
/usr/local/lib/node_modules/homebridge-tado/index.js:233
                    if (JSON.stringify(obj.setting.mode).match("HEAT")) {
                                                        ^

TypeError: Cannot read property 'match' of undefined
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-tado/index.js:233:57)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
pi@raspberrypi:~ $ 
```

```
                "accessory": "TADO",
                "name": "TadoKittchen",
                "homeID": "xxx",
                "username": "xxx",
                "password": "xxx",
                "zone": 2,
                "maxValue": 25,
                "minValue": 16,
                "useFanSpeed": false,
                "useSwing": false,
                "tadoMode": "TADO-MODE",
                "useFahrenheit": false
```

**Comment by nitaybz** [comment]
so I guess this is because the plugin does not support the heaters.... I don't have that device myself so it's quite hard for me to change the code to support this.

**Comment by nitaybz** [comment]
try https://github.com/Qonstrukt/homebridge-tadong
I thing this guy created support for the heaters

**Comment by StefanMeGit** [comment]
I dont he created something that works with the heaters. He also doesnt implement the ZONES. :( 

Anyway, thanks for the help!

**Comment by nitaybz** [comment]
Sorry I couldn't help more... maybe try to make an issue there and refer him to this plugin for implementing different zones and working with the new api authorization system.
