### ISSUE TITLE
Error crashes home bridge

### ISSUE THREAD

**Issue by jcastro** [ckuburlis/homebridge-tado#4]
Hello!

I'm getting this error 

```
May 09 21:48:07 raspberrypi homebridge[8981]: [2016-05-09 21:48:07] [Tado] Getting room temperature
May 09 21:48:27 raspberrypi homebridge[8981]: events.js:141
May 09 21:48:27 raspberrypi homebridge[8981]: throw er; // Unhandled 'error' event
May 09 21:48:27 raspberrypi homebridge[8981]: ^
May 09 21:48:27 raspberrypi homebridge[8981]: Error: getaddrinfo ENOTFOUND my.tado.com my.tado.com:443
May 09 21:48:27 raspberrypi homebridge[8981]: at errnoException (dns.js:27:10)
May 09 21:48:27 raspberrypi homebridge[8981]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
May 09 21:48:27 raspberrypi systemd[1]: homebridge@pi.service: main process exited, code=exited, status=1/FAILURE
May 09 21:48:27 raspberrypi systemd[1]: Unit homebridge@pi.service entered failed state.
```

As you can see, it crashes the whole homebridge process. I'm using homebridge-tadoheating (tried to open an issue on that repo but it seems disabled) plus I'm not sure if the problem could be on this repo as well.

Is there anything I can do to help with this? Thanks!

**Comment by nitaybz** [comment]
@jcastro Not an Issue anymore, update to the new version.
