### ISSUE TITLE
Support for new nodejs and npm versions

### ISSUE THREAD

**Issue by morilm** [ckuburlis/homebridge-tado#40]
Hi..
First of all, thanks for the great job and support!!!

Any idea when the plugin will be update to support nodejs v8 and npm v5?

Since the update plugin doesn't work.

I know I must go back to older npm, but I can't due to other dependencies....  so I need to wait.. :)

homebrid | TypeError: Cannot read property 'insideTemperature' of undefined
homebrid |     at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tado/index.js:336:76)
homebrid |     at emitNone (events.js:110:20)
homebrid |     at IncomingMessage.emit (events.js:207:7)
homebrid |     at endReadableNT (_stream_readable.js:1045:12)
homebrid |     at _combinedTickCallback (internal/process/next_tick.js:102:11)
homebrid |     at process._tickDomainCallback (internal/process/next_tick.js:198:9)

Thanks from the sunny spain

**Comment by nitaybz** [comment]
the plugin support any version of npm or nodejs, the issue is with npm ability to install or uninstall plugins in general.
try downgrading your npm in order to install the latest version:
`sudo npm install -g npm@4.6.1`
