### ISSUE TITLE
cannot reading temperatur/mode

### ISSUE THREAD

**Issue by Kiter1988** [ckuburlis/homebridge-tado#42]
Hi, i have install your plugin for my tado ac. 

Homebridge shows me some Issues, can you help me ? 
I have downgrade npm allready.
My Homekit says "No Answer". 

**1. Issue**
/usr/lib/node_modules/homebridge-tado/index.js:357
            if (obj.setting.temperature == null) {
                           ^
TypeError: Cannot read property 'temperature' of undefined
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tado/index.js:357:28)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**2. Issue**
/usr/lib/node_modules/homebridge-tado/index.js:157
            accessory.log("Current zone mode is " + obj.setting.mode);
                                                               ^
TypeError: Cannot read property 'mode' of undefined
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tado/index.js:157:64)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by nitaybz** [comment]
This plugin is not supported anymore. Install:
sudo npm install -g homebridge-tado-ac

**Comment by Kiter1988** [comment]
Thank you , now i have see it too^^
Big black letters :-P

**Comment by matthieulrg** [comment]
Hi,

I have the exact same problem (issue 2). Everything went well and after a few days same problem as you. I've reinstalled with sudo npm install -g homebridge-tado-ac, same thing. Everything is up to date, any idea ?

**Comment by nitaybz** [comment]
There is a change in the api,
Will be fixed in the next couple of days.
But it will be fixed on my plugin homebridge-tado-ac.
Please keep following there...

**Comment by nitaybz** [comment]
There is a change in the api,
Will be fixed in the next couple of days.
But it will be fixed on my plugin homebridge-tado-ac.
Please keep following there...

**Comment by matthieulrg** [comment]
Okay, thank you for your great work.
